<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Section' => '',
    'Add Section Article' => '',
    'All articles' => '',
    'Are you sure you want to delete this item?' => '',
    'Article' => '',
    'Articles' => '',
    'Cancel' => '',
    'Choose Article' => '',
    'Choose Section' => '',
    'Create' => '',
    'Create Article' => '',
    'Create Section' => '',
    'Delete' => '',
    'Edit sections' => '',
    'ID' => '',
    'Logout' => '',
    'Parent' => '',
    'Preview' => '',
    'Reset' => '',
    'Search' => '',
    'Section' => '',
    'Section Article' => '',
    'SectionArticle' => '',
    'Sections' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'id раздела' => '',
    'id статьи' => '',
    'Мета ключевые слова' => '',
    'Мета описание' => '',
    'Название раздела' => '',
    'Родительский раздел' => '',
    'Сортировка' => '',
    'Статус активности' => '',
    'Уникальное название раздела' => '',
    'Data is already expired' => '@@Data is already expired@@',
];
