<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Section' => 'Создать раздел',
    'Add Section Article' => 'Добавить связь',
    'All articles' => 'Все статьи',
    'Are you sure you want to delete this item?' => 'Вы уверены что хотите удалить этот элемент?',
    'Article' => 'Статья',
    'Articles' => 'Статьи',
    'Cancel' => 'Отмена',
    'Choose Article' => 'Выбрать статью',
    'Choose Section' => 'Выбрать раздел',
    'Close all' => 'Свернуть все',
    'Create' => 'Создать',
    'Create Article' => 'Создать статью',
    'Create Section' => 'Создать раздел',
    'Delete' => 'Удалить',
    'Edit Article' => 'Редактирование статьи',
    'Edit Section' => 'Редактирование раздела',
    'Edit menu' => 'Редактировать меню',
    'Edit sections' => 'Редактировать разделы',
    'Logout' => 'Выйти',
    'Open all' => 'Развернуть все',
    'Parent' => 'Родитель',
    'Reset' => 'Сброс',
    'Search' => 'Поиск',
    'Section' => 'Раздел',
    'Section Article' => 'Связи',
    'SectionArticle' => 'Связи',
    'Sections' => 'Разделы',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует.',
    'Update' => 'Обновить',
    'order' => 'Сортировка',
    'Create subsection from section ' => 'Создать подраздел в разделе ',
    'ID' => '',
    'id раздела' => '',
    'id статьи' => '',
    'Мета ключевые слова' => '',
    'Мета описание' => '',
    'Название раздела' => '',
    'Родительский раздел' => '',
    'Сортировка' => '',
    'Статус активности' => '',
    'Уникальное название раздела' => '',
    'Expand' => 'Развернуть',
    'Preview' => '@@Предпросмотр@@',
    'content' => '@@Контент@@',
];
